/**
 * Auto-generated Supabase types — PLACEHOLDER.
 *
 * This file is regenerated by running:
 *   pnpm supabase gen types typescript --linked > src/lib/supabase/database.types.ts
 *
 * The CI workflow runs the same command against the staging Supabase
 * project and fails the build on drift, so the version on disk always
 * matches the live schema.
 *
 * Until the project is linked (`supabase link --project-ref <ref>`) the
 * placeholder `Database` type below preserves type-safety for the
 * client helpers — every table is `unknown`, which forces explicit
 * narrowing at the call site so callers cannot accidentally rely on
 * stale shapes.
 */

export type Json = string | number | boolean | null | { [key: string]: Json } | Json[];

export interface Database {
  public: {
    Tables: Record<string, { Row: unknown; Insert: unknown; Update: unknown; Relationships: [] }>;
    Views: Record<string, { Row: unknown; Relationships: [] }>;
    Functions: Record<string, { Args: unknown; Returns: unknown }>;
    Enums: Record<string, string>;
    CompositeTypes: Record<string, unknown>;
  };
}
